name: Passo 5

on:
  workflow_run:
    workflows:
      - Rate Joke
    types:
      - completed

permissions:
  contents: write
  actions: write
  issues: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  find_exercise:
    if: github.event.workflow_run.conclusion == 'success'
    name: Encontrar Issue do Exercício
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  post_review_content:
    name: Postar conteúdo da revisão
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Obter templates de resposta
        uses: actions/checkout@v6
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Criar comentário - passo finalizado - revisão final a seguir
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/lesson-review.md

      - name: Criar comentário - adicionar conteúdo da revisão
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.REVIEW_FILE }}

      - name: Desabilitar workflow atual
        run: gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finalizar Exercício
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.7.1
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      exercise-title: "Create AI Powered Actions"
